### ISSUE TITLE
add timeout to verify

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/hubbot#17]
If verify takes longer than X minutes, end with a failure - this seems to happen from time to time during image creation.

I propose setting 60 minutes as the limit.

**Comment by mvollmer** [comment]
This was almost fixed as part of #18, but it has been reverted since we seem to lose all output from VERIFY.

**Comment by dperpeet** [comment]
added via https://github.com/cockpit-project/hubbot/commit/d9d7f3392641e1b077165457e1c5d8cbd98a6b9a
